services:
  web:
    image: nginx
    container_name: mgt-nginx
    restart: always
    ports:
      - "41128:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/src/app/public
  app:
    build: .
    container_name: app-fastadmin
    restart: always
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
